p1 = [{
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["voda", ""],
    slika: "slike/voda.jpg",
    zvuk: "zvuk/voda.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["ptica", ""],
    slika: "slike/ptica.jpg",
    zvuk: "zvuk/ptica.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["čokolada", ""],
    slika: "slike/cokolada.jpg",
    zvuk: "zvuk/čokolada.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["ćevapčić", ""],
    slika: "slike/cevapcic.jpg",
    zvuk: "zvuk/cevapcic.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["zračna luka", "aerodrom"],
    slika: "slike/aerodrom.jpg",
    zvuk: "zvuk/aerodrom.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["autobus", "bus"],
    slika: "slike/autobus.jpg",
    zvuk: "zvuk/autobus.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["automobil", "auto"],
    slika: "slike/auto.jpg",
    zvuk: "zvuk/auto.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["avion", "zrakoplov"],
    slika: "slike/avion.jpg",
    zvuk: "zvuk/avion.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
},  {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["banana", ""],
    slika: "slike/banana.jpg",
    zvuk: "zvuk/banana.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["banka", ""],
    slika: "slike/banka.jpg",
    zvuk: "zvuk/banka.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["beba", ""],
    slika: "slike/beba.jpg",
    zvuk: "zvuk/beba.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["bicikl", ""],
    slika: "slike/bicikl.jpg",
    zvuk: "zvuk/bicikl.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["blagajna", ""],
    slika: "slike/blagajna.jpg",
    zvuk: "zvuk/blagajna.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["bolnica", ""],
    slika: "slike/bolnica.jpg",
    zvuk: "zvuk/bolnica.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["brada", ""],
    slika: "slike/brada.jpg",
    zvuk: "zvuk/brada.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["brašno", ""],
    slika: "slike/brasno.jpg",
    zvuk: "zvuk/brašno.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["brdo", ""],
    slika: "slike/brdo.jpg",
    zvuk: "zvuk/brdo.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["breskva", ""],
    slika: "slike/breskva.jpg",
    zvuk: "zvuk/breskva.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["brod", ""],
    slika: "slike/brod.jpg",
    zvuk: "zvuk/brod.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["brokula", ""],
    slika: "slike/brokula.jpg",
    zvuk: "zvuk/brokula.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["burek", ""],
    slika: "slike/burek.jpg",
    zvuk: "zvuk/burek.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["cipela", ""],
    slika: "slike/cipela.jpg",
    zvuk: "zvuk/cipela.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["crkva", ""],
    slika: "slike/crkva.jpg",
    zvuk: "zvuk/crkva.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["cvijeće", "cvjetovi"],
    slika: "slike/cvijece.jpg",
    zvuk: "zvuk/cvijece.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["čaj", ""],
    slika: "slike/caj.jpg",
    zvuk: "zvuk/caj.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["čarapa", ""],
    slika: "slike/carapa.jpg",
    zvuk: "zvuk/carapa.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,

}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["čaša", ""],
    slika: "slike/casa.jpg",
    zvuk: "zvuk/casa.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["češnjak", "bijeli luk"],
    slika: "slike/cesnjak.jpg",
    zvuk: "zvuk/cesnjak.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
},  {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["diploma", ""],
    slika: "slike/diploma.jpg",
    zvuk: "zvuk/diploma.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
},  {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["prodavaonica", "trgovina"],
    slika: "slike/ducan.jpg",
    zvuk: "zvuk/ducan.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["dvorac", ""],
    slika: "slike/dvorac.jpg",
    zvuk: "zvuk/dvorac.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["džamija", ""],
    slika: "slike/dzamija.jpg",
    zvuk: "zvuk/dzamija.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["džem", "pekmez"],
    slika: "slike/dzem.jpg",
    zvuk: "zvuk/dzem.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["džep", ""],
    slika: "slike/dzep.jpg",
    zvuk: "zvuk/dzep.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["euro", ""],
    slika: "slike/euro.jpg",
    zvuk: "zvuk/euro.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
},  {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["gaće", "gaćice"],
    slika: "slike/gace.jpg",
    zvuk: "zvuk/gace.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["gitara", ""],
    slika: "slike/gitara.jpg",
    zvuk: "zvuk/gitara.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["glava", ""],
    slika: "slike/glava.jpg",
    zvuk: "zvuk/glava.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["gljiva", ""],
    slika: "slike/gljiva.jpg",
    zvuk: "zvuk/gljiva.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["grah", ""],
    slika: "slike/grah.jpg",
    zvuk: "zvuk/grah.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["haljina", ""],
    slika: "slike/haljina.jpg",
    zvuk: "zvuk/haljina.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["hlače", ""],
    slika: "slike/hlace.jpg",
    zvuk: "zvuk/hlače.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["hobotnica", ""],
    slika: "slike/hobotnica.jpg",
    zvuk: "zvuk/hobotnica.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["hodnik", ""],
    slika: "slike/hodnik.jpg",
    zvuk: "zvuk/hodnik.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["hotel", ""],
    slika: "slike/hotel.jpg",
    zvuk: "zvuk/hotel.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["igračka", ""],
    slika: "slike/igracka.jpg",
    zvuk: "zvuk/igračka.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
},  {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["izložba", ""],
    slika: "slike/izlozba.jpg",
    zvuk: "zvuk/izložba.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["jabuka", ""],
    slika: "slike/jabuka.jpg",
    zvuk: "zvuk/jabuka.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["jagoda", ""],
    slika: "slike/jagoda.jpg",
    zvuk: "zvuk/jagoda.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["jaje", ""],
    slika: "slike/jaje.jpg",
    zvuk: "zvuk/jaje.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["jakna", ""],
    slika: "slike/jakna.jpg",
    zvuk: "zvuk/jakna.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["jezero", ""],
    slika: "slike/jezero.jpg",
    zvuk: "zvuk/jezero.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["jezik", ""],
    slika: "slike/jezik.jpg",
    zvuk: "zvuk/jezik.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["jug", ""],
    slika: "slike/jug.jpg",
    zvuk: "zvuk/jug.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["kafić", ""],
    slika: "slike/kafic.jpg",
    zvuk: "zvuk/kafić.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["kapa", ""],
    slika: "slike/kapa.jpg",
    zvuk: "zvuk/kapa.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["kaput", ""],
    slika: "slike/kaput.jpg",
    zvuk: "zvuk/kaput.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["kartica", ""],
    slika: "slike/kartica.jpg",
    zvuk: "zvuk/kartica.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["kauč", ""],
    slika: "slike/kauc.jpg",
    zvuk: "zvuk/kauč.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["kava", ""],
    slika: "slike/kava.jpg",
    zvuk: "zvuk/kava.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["kazalište", ""],
    slika: "slike/kazaliste.jpg",
    zvuk: "zvuk/kazalište.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["kino", ""],
    slika: "slike/kino.jpg",
    zvuk: "zvuk/kino.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["kiša", ""],
    slika: "slike/kisa.jpg",
    zvuk: "zvuk/kiša.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["kišobran", ""],
    slika: "slike/kisobran.jpg",
    zvuk: "zvuk/kišobran.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["knjiga", ""],
    slika: "slike/knjiga.jpg",
    zvuk: "zvuk/knjiga.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["knjižnica", ""],
    slika: "slike/knjiznica.jpg",
    zvuk: "zvuk/knjižnica.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["kobasica", ""],
    slika: "slike/kobasica.jpg",
    zvuk: "zvuk/kobasica.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["kofer", ""],
    slika: "slike/kofer.jpg",
    zvuk: "zvuk/kofer.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["kolač", ""],
    slika: "slike/kolac.jpg",
    zvuk: "zvuk/kolač.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["koncert", ""],
    slika: "slike/koncert.jpg",
    zvuk: "zvuk/koncert.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["konj", ""],
    slika: "slike/konj.jpg",
    zvuk: "zvuk/konj.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["kosa", ""],
    slika: "slike/kosa.jpg",
    zvuk: "zvuk/kosa.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["kost", ""],
    slika: "slike/kost.jpg",
    zvuk: "zvuk/kost.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["košarka", ""],
    slika: "slike/kosarka.jpg",
    zvuk: "zvuk/košarka.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["košulja", ""],
    slika: "slike/kosulja.jpg",
    zvuk: "zvuk/košulja.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["krastavac", ""],
    slika: "slike/krastavac.jpg",
    zvuk: "zvuk/krastavac.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["krava", ""],
    slika: "slike/krava.jpg",
    zvuk: "zvuk/krava.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["krevet", ""],
    slika: "slike/krevet.jpg",
    zvuk: "zvuk/krevet.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["kruh", ""],
    slika: "slike/kruh.jpg",
    zvuk: "zvuk/kruh.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["krumpir", ""],
    slika: "slike/krumpir.jpg",
    zvuk: "zvuk/krumpir.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["kruška", ""],
    slika: "slike/kruska.jpg",
    zvuk: "zvuk/kruška.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["krv", ""],
    slika: "slike/krv.jpg",
    zvuk: "zvuk/krv.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["kuća", ""],
    slika: "slike/kuca.jpg",
    zvuk: "zvuk/kuća.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["kuhinja", ""],
    slika: "slike/kuhinja.jpg",
    zvuk: "zvuk/kuhinja.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["kuna", "kn"],
    slika: "slike/kuna.jpg",
    zvuk: "zvuk/kuna.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["kupaonica", ""],
    slika: "slike/kupaonica.jpg",
    zvuk: "zvuk/kupaonica.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["kupus", ""],
    slika: "slike/kupus.jpg",
    zvuk: "zvuk/kupus.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["kutija", ""],
    slika: "slike/kutija.jpg",
    zvuk: "zvuk/kutija.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["lampa", "svjetiljka"],
    slika: "slike/lampa.jpg",
    zvuk: "zvuk/lampa.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["lift", "dizalo"],
    slika: "slike/lift.jpg",
    zvuk: "zvuk/lift.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["lignja", ""],
    slika: "slike/lignja.jpg",
    zvuk: "zvuk/lignja.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["lijevo", ""],
    slika: "slike/lijevo.jpg",
    zvuk: "zvuk/lijevo.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["limun", ""],
    slika: "slike/limun.jpg",
    zvuk: "zvuk/limun.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["lišće", ""],
    slika: "slike/lisce.jpg",
    zvuk: "zvuk/lišće.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["lubenica", ""],
    slika: "slike/lubenica.jpg",
    zvuk: "zvuk/lubenica.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["mačka", ""],
    slika: "slike/macka.jpg",
    zvuk: "zvuk/mačka.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["majica", ""],
    slika: "slike/majica.jpg",
    zvuk: "zvuk/majica.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["mandarina", ""],
    slika: "slike/mandarina.jpg",
    zvuk: "zvuk/mandarina.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["marelica", ""],
    slika: "slike/marelica.jpg",
    zvuk: "zvuk/marelica.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["maslac", ""],
    slika: "slike/maslac.jpg",
    zvuk: "zvuk/maslac.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["maslina", ""],
    slika: "slike/maslina.jpg",
    zvuk: "zvuk/maslina.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["med", ""],
    slika: "slike/med.jpg",
    zvuk: "zvuk/med.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["medvjed", ""],
    slika: "slike/medvjed.jpg",
    zvuk: "zvuk/medvjed.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["mjesec", ""],
    slika: "slike/mjesec.jpg",
    zvuk: "zvuk/mjesec.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["mlijeko", ""],
    slika: "slike/mlijeko.jpg",
    zvuk: "zvuk/mlijeko.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["mobitel", "telefon"],
    slika: "slike/mobitel.jpg",
    zvuk: "zvuk/mobitel.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["more", ""],
    slika: "slike/more.jpg",
    zvuk: "zvuk/more.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["most", ""],
    slika: "slike/most.jpg",
    zvuk: "zvuk/most.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["mrkva", ""],
    slika: "slike/mrkva.jpg",
    zvuk: "zvuk/mrkva.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
},  {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["muzej", ""],
    slika: "slike/muzej.jpg",
    zvuk: "zvuk/muzej.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["naočale", ""],
    slika: "slike/naocale.jpg",
    zvuk: "zvuk/naočale.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["naranča", ""],
    slika: "slike/naranca.jpg",
    zvuk: "zvuk/naranča.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["nebo", ""],
    slika: "slike/nebo.jpg",
    zvuk: "zvuk/nebo.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["neboder", ""],
    slika: "slike/neboder.jpg",
    zvuk: "zvuk/neboder.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["noga", ""],
    slika: "slike/noga.jpg",
    zvuk: "zvuk/noga.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["nogomet", ""],
    slika: "slike/nogomet.jpg",
    zvuk: "zvuk/nogomet.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["nos", ""],
    slika: "slike/nos.jpg",
    zvuk: "zvuk/nos.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["novac", ""],
    slika: "slike/novac.jpg",
    zvuk: "zvuk/novac.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["obrva", ""],
    slika: "slike/obrva.jpg",
    zvuk: "zvuk/obrva.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["odijelo", ""],
    slika: "slike/odijelo.jpg",
    zvuk: "zvuk/odijelo.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["odjeća", "roba"],
    slika: "slike/odjeca.jpg",
    zvuk: "zvuk/odjeća.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["ogledalo", "zrcalo"],
    slika: "slike/ogledalo.jpg",
    zvuk: "zvuk/ogledalo.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["oko", ""],
    slika: "slike/oko.jpg",
    zvuk: "zvuk/oko.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["olovka", ""],
    slika: "slike/olovka.jpg",
    zvuk: "zvuk/olovka.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["orah", ""],
    slika: "slike/orah.jpg",
    zvuk: "zvuk/orah.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["ormar", ""],
    slika: "slike/ormar.jpg",
    zvuk: "zvuk/ormar.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["palačinka", ""],
    slika: "slike/palacinka.jpg",
    zvuk: "zvuk/palačinka.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["papir", ""],
    slika: "slike/papir.jpg",
    zvuk: "zvuk/papir.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["paprika", ""],
    slika: "slike/paprika.jpg",
    zvuk: "zvuk/paprika.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["papuča", "papuče"],
    slika: "slike/papuca.jpg",
    zvuk: "zvuk/papuča.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["pas", ""],
    slika: "slike/pas.jpg",
    zvuk: "zvuk/pas.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["patlidžan", ""],
    slika: "slike/patlidzan.jpg",
    zvuk: "zvuk/patliđan.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["pauk", ""],
    slika: "slike/pauk.jpg",
    zvuk: "zvuk/pauk.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["pećnica", ""],
    slika: "slike/pecnica.jpg",
    zvuk: "zvuk/pećnica.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["pidžama", ""],
    slika: "slike/pidzama.jpg",
    zvuk: "zvuk/pidžama.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["pismo", ""],
    slika: "slike/pismo.jpg",
    zvuk: "zvuk/pismo.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["pivo", ""],
    slika: "slike/pivo.jpg",
    zvuk: "zvuk/pivo.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["planina", ""],
    slika: "slike/planina.jpg",
    zvuk: "zvuk/planina.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["plaža", "more"],
    slika: "slike/plaza.jpg",
    zvuk: "zvuk/plaža.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["ploča", ""],
    slika: "slike/ploca.jpg",
    zvuk: "zvuk/ploča.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["poklon", "dar"],
    slika: "slike/poklon.jpg",
    zvuk: "zvuk/poklon.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["polica", ""],
    slika: "slike/polica.jpg",
    zvuk: "zvuk/polica.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
},  {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["policija", ""],
    slika: "slike/policija.jpg",
    zvuk: "zvuk/policija.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["potpis", ""],
    slika: "slike/potpis.jpg",
    zvuk: "zvuk/potpis.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["povrće", ""],
    slika: "slike/povrce.jpg",
    zvuk: "zvuk/povrće.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
},  {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["prozor", ""],
    slika: "slike/prozor.jpg",
    zvuk: "zvuk/prozor.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["pulover", ""],
    slika: "slike/pulover.jpg",
    zvuk: "zvuk/pulover.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["račun", ""],
    slika: "slike/racun.jpg",
    zvuk: "zvuk/račun.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["računalo", "kompjuter"],
    slika: "slike/racunalo.jpg",
    zvuk: "zvuk/računalo.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["recept", ""],
    slika: "slike/recept.jpg",
    zvuk: "zvuk/recept.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["restoran", ""],
    slika: "slike/restoran.jpg",
    zvuk: "zvuk/restoran.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["riba", ""],
    slika: "slike/riba.jpg",
    zvuk: "zvuk/riba.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["rijeka", ""],
    slika: "slike/rijeka.jpg",
    zvuk: "zvuk/rijeka.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["riža", ""],
    slika: "slike/riza.jpg",
    zvuk: "zvuk/riža.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["rječnik", ""],
    slika: "slike/rjecnik.jpg",
    zvuk: "zvuk/rječnik.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["ruka", ""],
    slika: "slike/ruka.jpg",
    zvuk: "zvuk/ruka.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["rukavica", ""],
    slika: "slike/rukavica.jpg",
    zvuk: "zvuk/rukavica.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["rukomet", ""],
    slika: "slike/rukomet.jpg",
    zvuk: "zvuk/rukomet.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["salata", ""],
    slika: "slike/salata.jpg",
    zvuk: "zvuk/salata.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["sendvič", ""],
    slika: "slike/sendvic.jpg",
    zvuk: "zvuk/sendvič.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["sinagoga", ""],
    slika: "slike/sinagoga.jpg",
    zvuk: "zvuk/sinagoga.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["sir", ""],
    slika: "slike/sir.jpg",
    zvuk: "zvuk/sir.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
},{
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["sladoled", ""],
    slika: "slike/sladoled.jpg",
    zvuk: "zvuk/sladoled.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["slika", ""],
    slika: "slike/slika.jpg",
    zvuk: "zvuk/slika.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["snijeg", ""],
    slika: "slike/snijeg.jpg",
    zvuk: "zvuk/snijeg.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["srce", ""],
    slika: "slike/srce.jpg",
    zvuk: "zvuk/srce.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["stablo", "drvo"],
    slika: "slike/stablo.jpg",
    zvuk: "zvuk/stablo.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["stol", ""],
    slika: "slike/stol.jpg",
    zvuk: "zvuk/stol.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["stolica", ""],
    slika: "slike/stolica.jpg",
    zvuk: "zvuk/stolica.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["svinja", ""],
    slika: "slike/svinja.jpg",
    zvuk: "zvuk/svinja.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["šalica", ""],
    slika: "slike/salica.jpg",
    zvuk: "zvuk/šalica.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["šećer", ""],
    slika: "slike/secer.jpg",
    zvuk: "zvuk/šećer.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["šešir", ""],
    slika: "slike/sesir.jpg",
    zvuk: "zvuk/šešir.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["škola", ""],
    slika: "slike/skola.jpg",
    zvuk: "zvuk/škola.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["šljiva", ""],
    slika: "slike/sljiva.jpg",
    zvuk: "zvuk/šljiva.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["šuma", ""],
    slika: "slike/suma.jpg",
    zvuk: "zvuk/suma.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["tanjur", ""],
    slika: "slike/tanjur.jpg",
    zvuk: "zvuk/tanjur.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["televizor", ""],
    slika: "slike/televizor.jpg",
    zvuk: "zvuk/televizor.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["tikvica", ""],
    slika: "slike/tikvica.jpg",
    zvuk: "zvuk/tikvica.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["tjestenina", ""],
    slika: "slike/tjestenina.jpg",
    zvuk: "zvuk/tjestenina.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["torba", ""],
    slika: "slike/torba.jpg",
    zvuk: "zvuk/torba.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["tramvaj", ""],
    slika: "slike/tramvaj.jpg",
    zvuk: "zvuk/tramvaj.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["trepavica", "trepavice"],
    slika: "slike/trepavica.jpg",
    zvuk: "zvuk/trepavica.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["trešnja", ""],
    slika: "slike/tresnja.jpg",
    zvuk: "zvuk/trešnja.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["tržnica", ""],
    slika: "slike/trznica.jpg",
    zvuk: "zvuk/tržnica.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["ulaz", ""],
    slika: "slike/ulaz.jpg",
    zvuk: "zvuk/ulaz.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["ulica", ""],
    slika: "slike/ulica.jpg",
    zvuk: "zvuk/ulica.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["ured", ""],
    slika: "slike/ured.jpg",
    zvuk: "zvuk/ured.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
},  {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["vjenčanje", ""],
    slika: "slike/vjencanje.jpg",
    zvuk: "zvuk/vjenčanje.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["voće", ""],
    slika: "slike/voce.jpg",
    zvuk: "zvuk/voce.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["vrata", ""],
    slika: "slike/vrata.jpg",
    zvuk: "zvuk/vrata.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["zastava", ""],
    slika: "slike/zastava.jpg",
    zvuk: "zvuk/zastava.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["zmija", ""],
    slika: "slike/zmija.jpg",
    zvuk: "zvuk/zmija.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}, {
    question: "popuni",
    vrijeme: "pitanja",
    correctAnswer: ["zvijezda", ""],
    slika: "slike/zvijezda.jpg",
    zvuk: "zvuk/zvijezda.mp3",
    boja_pozadine: "#FCE4EC",
    time: 20,
}
]